# GitHub Sponsors Configuration
# This file adds a "Sponsor" button to your repository

# Ko-fi username
ko_fi: gary19gts

# Custom links (optional - you can add more platforms later)
custom: ['https://ko-fi.com/gary19gts']
